export class FlatDetails {
    bedRoom: number;
    approvalNo: number;
    blockName: string;
    projectType: string;
    decorationCondition: string;
    facingNo: number;
    flatNo: number;
    flatPlaceofStorid: number;
    flatSize: number;
    gym: number;
    itemNo: number;
    projectTypeNo: number;
    itemType: number;
    kitchen: number;
    livingAndDining: number;
    numberOfLift: number;
    parkingFlag: number;
    parkingPrice: number;
    plotSize: number;
    plotType: number;
    price: number;
    projectNo: number;
    roadSize: number;
    swimmingPool: number;
    toilets: number;
    totalPrice: number;
    itemId: string;
    varanda: number;
    roadSizeNo: number;
    flatType: string;
    projectLocation: string;
    blockNameFrom: string;
    blockNameTo: string;
    multipartFile: string;
    videoTitle: string;
    videoMetaTag: string;
    projectName: string;
    approvalId: string;
    projectId: string;
    uomShort: string;

    constructor(options: any = {}) {
        this.bedRoom = options.bedRoom || (options.bedRoom === 0 ? 0: null);
        this.approvalNo = options.approvalNo || (options.approvalNo === 0 ? 0 : null);
        this.blockName = options.blockName || '';
        this.projectType = options.projectType || '';
        this.decorationCondition = options.decorationCondition || '';
        this.facingNo = options.facingNo || (options.facingNo === 0 ? 0 : null);
        this.flatNo = options.flatNo || (options.flatNo === 0 ? 0 : null);
        this.flatPlaceofStorid = options.flatPlaceofStorid || (options.flatPlaceofStorid === 0 ? 0 : null);
        this.flatSize = options.flatSize || (options.flatSize === 0 ? 0 : null);
        this.gym = options.gym || (options.gym == 0 ? 0 : null);
        this.itemId = options.itemId || "";
        this.flatType = options.flatType || "";
        this.projectLocation = options.projectLocation || "";
        this.uomShort = options.uomShort || '';
        this.itemNo = options.itemNo || (options.itemNo === 0 ? 0 : null);
        this.projectTypeNo = options.projectTypeNo || (options.projectTypeNo === 0 ? 0 : null);
        this.itemType = options.itemType || (options.itemType === 0 ? 0 : null);
        this.kitchen = options.kitchen || (options.kitchen === 0 ? 0 : null);
        this.livingAndDining = options.livingAndDining || (options.livingAndDining === 0 ? 0 : null);
        this.numberOfLift = options.numberOfLift || (options.numberOfLift === 0 ? 0 : null);
        this.parkingFlag = (options.parkingFlag) || (options.parkingFlag == 0 ? 0 : null);
        this.parkingPrice = options.parkingPrice || (options.parkingPrice === 0 ? 0 : null);
        this.plotSize = options.plotSize || (options.plotSize === 0 ? 0 : null);
        this.plotType = options.plotType || (options.plotType === 0 ? 0 : null);
        this.price = options.price || (options.price === 0 ? 0 : null);
        this.projectNo = options.projectNo || (options.projectNo === 0 ? 0 : null);
        this.roadSize = options.roadSize || (options.roadSize === 0 ? 0 : null);
        this.swimmingPool = options.swimmingPool || (options.swimmingPool === 0 ? 0 : null);
        this.toilets = options.toilets || (options.toilets === 0 ? 0 : null);
        this.totalPrice = options.totalPrice || (options.totalPrice === 0 ? 0 : null);
        this.varanda = options.varanda || (options.varanda === 0 ? 0 : null);
        this.roadSizeNo = options.roadSizeNo || (options.roadSizeNo === 0 ? 0 : null);
        this.blockNameFrom = options.blockNameFrom || '';
        this.blockNameTo = options.blockNameTo || '';
        this.multipartFile = options.multipartFile || '';
        this.videoTitle = options.videoTitle || '';
        this.videoMetaTag = options.videoMetaTag || '';
        this.projectName = options.projectName || '';
        this.approvalId = options.approvalId || '';
        this.projectId = options.projectId || '';
    }
}
