let atoz = [
    { VALUE: 'A', TEXT: 'A' },
    { VALUE: 'B', TEXT: 'B' },
    { VALUE: 'C', TEXT: 'C' },
    { VALUE: 'D', TEXT: 'D' },
    { VALUE: 'E', TEXT: 'E' },
    { VALUE: 'F', TEXT: 'F' },
    { VALUE: 'G', TEXT: 'G' },
    { VALUE: 'H', TEXT: 'H' },
    { VALUE: 'I', TEXT: 'I' },
    { VALUE: 'J', TEXT: 'J' },
    { VALUE: 'K', TEXT: 'K' },
    { VALUE: 'L', TEXT: 'L' },
    { VALUE: 'M', TEXT: 'M' },
    { VALUE: 'N', TEXT: 'N' },
    { VALUE: 'O', TEXT: 'O' },
    { VALUE: 'P', TEXT: 'P' },
    { VALUE: 'Q', TEXT: 'Q' },
    { VALUE: 'R', TEXT: 'R' },
    { VALUE: 'S', TEXT: 'S' },
    { VALUE: 'T', TEXT: 'T' },
    { VALUE: 'U', TEXT: 'U' },
    { VALUE: 'V', TEXT: 'V' },
    { VALUE: 'W', TEXT: 'W' },
    { VALUE: 'X', TEXT: 'X' },
    { VALUE: 'Y', TEXT: 'Y' },
    { VALUE: 'Y', TEXT: 'Y' },
    { VALUE: 'Z', TEXT: 'Z' },
]

let countryList =
    [
        { VALUE: 'AF', TEXT: 'Afghanistan' },
        { VALUE: 'AX', TEXT: 'Åland Islands' },
        { VALUE: 'AL', TEXT: 'Albania' },
        { VALUE: 'DZ', TEXT: 'Algeria' },
        { VALUE: 'AS', TEXT: 'American Samoa' },
        { VALUE: 'AD', TEXT: 'Andorra' },
        { VALUE: 'AO', TEXT: 'Angola' },
        { VALUE: 'AI', TEXT: 'Anguilla' },
        { VALUE: 'AQ', TEXT: 'Antarctica' },
        { VALUE: 'AG', TEXT: 'Antigua and Barbuda' },
        { VALUE: 'AR', TEXT: 'Argentina' },
        { VALUE: 'AM', TEXT: 'Armenia' },
        { VALUE: 'AW', TEXT: 'Aruba' },
        { VALUE: 'AU', TEXT: 'Australia' },
        { VALUE: 'AT', TEXT: 'Austria' },
        { VALUE: 'AZ', TEXT: 'Azerbaijan' },
        { VALUE: 'BS', TEXT: 'Bahamas' },
        { VALUE: 'BH', TEXT: 'Bahrain' },
        { VALUE: 'BD', TEXT: 'Bangladesh' },
        { VALUE: 'BB', TEXT: 'Barbados' },
        { VALUE: 'BY', TEXT: 'Belarus' },
        { VALUE: 'BE', TEXT: 'Belgium' },
        { VALUE: 'BZ', TEXT: 'Belize' },
        { VALUE: 'BJ', TEXT: 'Benin' },
        { VALUE: 'BM', TEXT: 'Bermuda' },
        { VALUE: 'BT', TEXT: 'Bhutan' },
        { VALUE: 'BO', TEXT: 'Bolivia, Plurinational State of' },
        { VALUE: 'BQ', TEXT: 'Bonaire, Sint Eustatius and Saba' },
        { VALUE: 'BA', TEXT: 'Bosnia and Herzegovina' },
        { VALUE: 'BW', TEXT: 'Botswana' },
        { VALUE: 'BV', TEXT: 'Bouvet Island' },
        { VALUE: 'BR', TEXT: 'Brazil' },
        { VALUE: 'IO', TEXT: 'British Indian Ocean Territory' },
        { VALUE: 'BN', TEXT: 'Brunei Darussalam' },
        { VALUE: 'BG', TEXT: 'Bulgaria' },
        { VALUE: 'BF', TEXT: 'Burkina Faso' },
        { VALUE: 'BI', TEXT: 'Burundi' },
        { VALUE: 'KH', TEXT: 'Cambodia' },
        { VALUE: 'CM', TEXT: 'Cameroon' },
        { VALUE: 'CA', TEXT: 'Canada' },
        { VALUE: 'CV', TEXT: 'Cape Verde' },
        { VALUE: 'KY', TEXT: 'Cayman Islands' },
        { VALUE: 'CF', TEXT: 'Central African Republic' },
        { VALUE: 'TD', TEXT: 'Chad' },
        { VALUE: 'CL', TEXT: 'Chile' },
        { VALUE: 'CN', TEXT: 'China' },
        { VALUE: 'CX', TEXT: 'Christmas Island' },
        { VALUE: 'CC', TEXT: 'Cocos (Keeling) Islands' },
        { VALUE: 'CO', TEXT: 'Colombia' },
        { VALUE: 'KM', TEXT: 'Comoros' },
        { VALUE: 'CG', TEXT: 'Congo' },
        { VALUE: 'CD', TEXT: 'Congo, the Democratic Republic of the' },
        { VALUE: 'CK', TEXT: 'Cook Islands' },
        { VALUE: 'CR', TEXT: 'Costa Rica' },
        { VALUE: 'CI', TEXT: 'Côte d\'Ivoire' },
        { VALUE: 'HR', TEXT: 'Croatia' },
        { VALUE: 'CU', TEXT: 'Cuba' },
        { VALUE: 'CW', TEXT: 'Curaçao' },
        { VALUE: 'CY', TEXT: 'Cyprus' },
        { VALUE: 'CZ', TEXT: 'Czech Republic' },
        { VALUE: 'DK', TEXT: 'Denmark' },
        { VALUE: 'DJ', TEXT: 'Djibouti' },
        { VALUE: 'DM', TEXT: 'Dominica' },
        { VALUE: 'DO', TEXT: 'Dominican Republic' },
        { VALUE: 'EC', TEXT: 'Ecuador' },
        { VALUE: 'EG', TEXT: 'Egypt' },
        { VALUE: 'SV', TEXT: 'El Salvador' },
        { VALUE: 'GQ', TEXT: 'Equatorial Guinea' },
        { VALUE: 'ER', TEXT: 'Eritrea' },
        { VALUE: 'EE', TEXT: 'Estonia' },
        { VALUE: 'ET', TEXT: 'Ethiopia' },
        { VALUE: 'FK', TEXT: 'Falkland Islands (Malvinas' },
        { VALUE: 'FO', TEXT: 'Faroe Islands' },
        { VALUE: 'FJ', TEXT: 'Fiji' },
        { VALUE: 'FI', TEXT: 'Finland' },
        { VALUE: 'FR', TEXT: 'France' },
        { VALUE: 'GF', TEXT: 'French Guiana' },
        { VALUE: 'PF', TEXT: 'French Polynesia' },
        { VALUE: 'TF', TEXT: 'French Southern Territories' },
        { VALUE: 'GA', TEXT: 'Gabon' },
        { VALUE: 'GM', TEXT: 'Gambia' },
        { VALUE: 'GE', TEXT: 'Georgia' },
        { VALUE: 'DE', TEXT: 'Germany' },
        { VALUE: 'GH', TEXT: 'Ghana' },
        { VALUE: 'GI', TEXT: 'Gibraltar' },
        { VALUE: 'GR', TEXT: 'Greece' },
        { VALUE: 'GL', TEXT: 'Greenland' },
        { VALUE: 'GD', TEXT: 'Grenada' },
        { VALUE: 'GP', TEXT: 'Guadeloupe' },
        { VALUE: 'GU', TEXT: 'Guam' },
        { VALUE: 'GT', TEXT: 'Guatemala' },
        { VALUE: 'GG', TEXT: 'Guernsey' },
        { VALUE: 'GN', TEXT: 'Guinea' },
        { VALUE: 'GW', TEXT: 'Guinea-Bissau' },
        { VALUE: 'GY', TEXT: 'Guyana' },
        { VALUE: 'HT', TEXT: 'Haiti' },
        { VALUE: 'HM', TEXT: 'Heard Island and McDonald Islands' },
        { VALUE: 'VA', TEXT: 'Holy See (Vatican City State)' },
        { VALUE: 'HN', TEXT: 'Honduras' },
        { VALUE: 'HK', TEXT: 'Hong Kong' },
        { VALUE: 'HU', TEXT: 'Hungary' },
        { VALUE: 'IS', TEXT: 'Iceland' },
        { VALUE: 'IN', TEXT: 'India' },
        { VALUE: 'ID', TEXT: 'Indonesia' },
        { VALUE: 'IR', TEXT: 'Iran, Islamic Republic of' },
        { VALUE: 'IQ', TEXT: 'Iraq' },
        { VALUE: 'IE', TEXT: 'Ireland' },
        { VALUE: 'IM', TEXT: 'Isle of Man' },
        { VALUE: 'IL', TEXT: 'Israel' },
        { VALUE: 'IT', TEXT: 'Italy' },
        { VALUE: 'JM', TEXT: 'Jamaica' },
        { VALUE: 'JP', TEXT: 'Japan' },
        { VALUE: 'JE', TEXT: 'Jersey' },
        { VALUE: 'JO', TEXT: 'Jordan' },
        { VALUE: 'KZ', TEXT: 'Kazakhstan' },
        { VALUE: 'KE', TEXT: 'Kenya' },
        { VALUE: 'KI', TEXT: 'Kiribati' },
        { VALUE: 'KP', TEXT: 'Korea, Democratic People\'s Republic of' },
        { VALUE: 'KR', TEXT: 'Korea, Republic of' },
        { VALUE: 'KW', TEXT: 'Kuwait' },
        { VALUE: 'KG', TEXT: 'Kyrgyzstan' },
        { VALUE: 'LA', TEXT: 'Lao People\'s Democratic Republic' },
        { VALUE: 'LV', TEXT: 'Latvia' },
        { VALUE: 'LB', TEXT: 'Lebanon' },
        { VALUE: 'LS', TEXT: 'Lesotho' },
        { VALUE: 'LR', TEXT: 'Liberia' },
        { VALUE: 'LY', TEXT: 'Libya' },
        { VALUE: 'LI', TEXT: 'Liechtenstein' },
        { VALUE: 'LT', TEXT: 'Lithuania' },
        { VALUE: 'LU', TEXT: 'Luxembourg' },
        { VALUE: 'MO', TEXT: 'Macao' },
        { VALUE: 'MK', TEXT: 'Macedonia, the former Yugoslav Republic of' },
        { VALUE: 'MG', TEXT: 'Madagascar' },
        { VALUE: 'MW', TEXT: 'Malawi' },
        { VALUE: 'MY', TEXT: 'Malaysia' },
        { VALUE: 'MV', TEXT: 'Maldives' },
        { VALUE: 'ML', TEXT: 'Mali' },
        { VALUE: 'MT', TEXT: 'Malta' },
        { VALUE: 'MH', TEXT: 'Marshall Islands' },
        { VALUE: 'MQ', TEXT: 'Martinique' },
        { VALUE: 'MR', TEXT: 'Mauritania' },
        { VALUE: 'MU', TEXT: 'Mauritius' },
        { VALUE: 'YT', TEXT: 'Mayotte' },
        { VALUE: 'MX', TEXT: 'Mexico' },
        { VALUE: 'FM', TEXT: 'Micronesia, Federated States of' },
        { VALUE: 'MD', TEXT: 'Moldova, Republic of' },
        { VALUE: 'MC', TEXT: 'Monaco' },
        { VALUE: 'MN', TEXT: 'Mongolia' },
        { VALUE: 'ME', TEXT: 'Montenegro' },
        { VALUE: 'MS', TEXT: 'Montserrat' },
        { VALUE: 'MA', TEXT: 'Morocco' },
        { VALUE: 'MZ', TEXT: 'Mozambique' },
        { VALUE: 'MM', TEXT: 'Myanmar' },
        { VALUE: 'NA', TEXT: 'Namibia' },
        { VALUE: 'NR', TEXT: 'Nauru' },
        { VALUE: 'NP', TEXT: 'Nepal' },
        { VALUE: 'NL', TEXT: 'Netherlands' },
        { VALUE: 'NC', TEXT: 'New Caledonia' },
        { VALUE: 'NZ', TEXT: 'New Zealand' },
        { VALUE: 'NI', TEXT: 'Nicaragua' },
        { VALUE: 'NE', TEXT: 'Niger' },
        { VALUE: 'NG', TEXT: 'Nigeria' },
        { VALUE: 'NU', TEXT: 'Niue' },
        { VALUE: 'NF', TEXT: 'Norfolk Island' },
        { VALUE: 'MP', TEXT: 'Northern Mariana Islands' },
        { VALUE: 'NO', TEXT: 'Norway' },
        { VALUE: 'OM', TEXT: 'Oman' },
        { VALUE: 'PK', TEXT: 'Pakistan' },
        { VALUE: 'PW', TEXT: 'Palau' },
        { VALUE: 'PS', TEXT: 'Palestinian Territory, Occupied' },
        { VALUE: 'PA', TEXT: 'Panama' },
        { VALUE: 'PG', TEXT: 'Papua New Guinea' },
        { VALUE: 'PY', TEXT: 'Paraguay' },
        { VALUE: 'PE', TEXT: 'Peru' },
        { VALUE: 'PH', TEXT: 'Philippines' },
        { VALUE: 'PN', TEXT: 'Pitcairn' },
        { VALUE: 'PL', TEXT: 'Poland' },
        { VALUE: 'PT', TEXT: 'Portugal' },
        { VALUE: 'PR', TEXT: 'Puerto Rico' },
        { VALUE: 'QA', TEXT: 'Qatar' },
        { VALUE: 'RE', TEXT: 'Réunion' },
        { VALUE: 'RO', TEXT: 'Romania' },
        { VALUE: 'RU', TEXT: 'Russian Federation' },
        { VALUE: 'RW', TEXT: 'Rwanda' },
        { VALUE: 'BL', TEXT: 'Saint Barthélemy' },
        { VALUE: 'SH', TEXT: 'Saint Helena, Ascension and Tristan da Cunha' },
        { VALUE: 'KN', TEXT: 'Saint Kitts and Nevis' },
        { VALUE: 'LC', TEXT: 'Saint Lucia' },
        { VALUE: 'MF', TEXT: 'Saint Martin (French part' },
        { VALUE: 'PM', TEXT: 'Saint Pierre and Miquelon' },
        { VALUE: 'VC', TEXT: 'Saint Vincent and the Grenadines' },
        { VALUE: 'WS', TEXT: 'Samoa' },
        { VALUE: 'SM', TEXT: 'San Marino' },
        { VALUE: 'ST', TEXT: 'Sao Tome and Principe' },
        { VALUE: 'SA', TEXT: 'Saudi Arabia' },
        { VALUE: 'SN', TEXT: 'Senegal' },
        { VALUE: 'RS', TEXT: 'Serbia' },
        { VALUE: 'SC', TEXT: 'Seychelles' },
        { VALUE: 'SL', TEXT: 'Sierra Leone' },
        { VALUE: 'SG', TEXT: 'Singapore' },
        { VALUE: 'SX', TEXT: 'Sint Maarten (Dutch part' },
        { VALUE: 'SK', TEXT: 'Slovakia' },
        { VALUE: 'SI', TEXT: 'Slovenia' },
        { VALUE: 'SB', TEXT: 'Solomon Islands' },
        { VALUE: 'SO', TEXT: 'Somalia' },
        { VALUE: 'ZA', TEXT: 'South Africa' },
        { VALUE: 'GS', TEXT: 'South Georgia and the South Sandwich Islands' },
        { VALUE: 'SS', TEXT: 'South Sudan' },
        { VALUE: 'ES', TEXT: 'Spain' },
        { VALUE: 'LK', TEXT: 'Sri Lanka' },
        { VALUE: 'SD', TEXT: 'Sudan' },
        { VALUE: 'SR', TEXT: 'Suriname' },
        { VALUE: 'SJ', TEXT: 'Svalbard and Jan Mayen' },
        { VALUE: 'SZ', TEXT: 'Swaziland' },
        { VALUE: 'SE', TEXT: 'Sweden' },
        { VALUE: 'CH', TEXT: 'Switzerland' },
        { VALUE: 'SY', TEXT: 'Syrian Arab Republic' },
        { VALUE: 'TW', TEXT: 'Taiwan, Province of China' },
        { VALUE: 'TJ', TEXT: 'Tajikistan' },
        { VALUE: 'TZ', TEXT: 'Tanzania, United Republic of' },
        { VALUE: 'TH', TEXT: 'Thailand' },
        { VALUE: 'TL', TEXT: 'Timor-Leste' },
        { VALUE: 'TG', TEXT: 'Togo' },
        { VALUE: 'TK', TEXT: 'Tokelau' },
        { VALUE: 'TO', TEXT: 'Tonga' },
        { VALUE: 'TT', TEXT: 'Trinidad and Tobago' },
        { VALUE: 'TN', TEXT: 'Tunisia' },
        { VALUE: 'TR', TEXT: 'Turkey' },
        { VALUE: 'TM', TEXT: 'Turkmenistan' },
        { VALUE: 'TC', TEXT: 'Turks and Caicos Islands' },
        { VALUE: 'TV', TEXT: 'Tuvalu' },
        { VALUE: 'UG', TEXT: 'Uganda' },
        { VALUE: 'UA', TEXT: 'Ukraine' },
        { VALUE: 'AE', TEXT: 'United Arab Emirates' },
        { VALUE: 'GB', TEXT: 'United Kingdom' },
        { VALUE: 'US', TEXT: 'United States' },
        { VALUE: 'UM', TEXT: 'United States Minor Outlying Islands' },
        { VALUE: 'UY', TEXT: 'Uruguay' },
        { VALUE: 'UZ', TEXT: 'Uzbekistan' },
        { VALUE: 'VU', TEXT: 'Vanuatu' },
        { VALUE: 'VE', TEXT: 'Venezuela, Bolivarian Republic of' },
        { VALUE: 'VN', TEXT: 'Viet Nam' },
        { VALUE: 'VG', TEXT: 'Virgin Islands, British' },
        { VALUE: 'VI', TEXT: 'Virgin Islands, U.S' },
        { VALUE: 'WF', TEXT: 'Wallis and Futuna' },
        { VALUE: 'EH', TEXT: 'Western Sahara' },
        { VALUE: 'YE', TEXT: 'Yemen' },
        { VALUE: 'ZM', TEXT: 'Zambia' },
        { VALUE: 'ZW', TEXT: 'Zimbabwe' }
    ]

export const fixedValues: any = {
    atoz: atoz,
    countryList: countryList,
}
